train:
  epoch: 1000
  snapshot_interval: 2000
  batchsize: 16
  validsize: 4
  mask: true

dataset:
  extension: ".png"
  train_size: 256
  valid_size: 256
  color_space: "rgb"
  line_space: "rgb"

model:
  generator:
    in_ch: 6
    lr: 0.0002
    b1: 0.5
    b2: 0.99
    mode: "train"
  discriminator:
    lr: 0.0002
    b1: 0.5
    b2: 0.99
    mode: "train"

loss:
  content: 10.0
  adv: 1.0
  gp: 0.5
  center: "zero"
